- job_name: node
  static_configs:
  - targets: ['3.22.71.171:9100']

# Blackbox
- job_name: my-blackbox
  static_configs:
  - targets: ['prometheus-blackbox-prometheus-blackbox-exporter:9115']


- job_name: 'blackbox-external-targets'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - https://www.google.com
      - http://3.22.71.171/events
      - http://3.22.71.171/events/1
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-blackbox-prometheus-blackbox-exporter:9115

- job_name: "blackbox-kubernetes-services"
  metrics_path: /probe
  params:
    module: [http_2xx]
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  # Example relabel to probe only some services that have "example.io/should_be_probed = true" annotation
  #  - source_labels: [__meta_kubernetes_service_annotation_example_io_should_be_probed]
  #    action: keep
  #    regex: true
    - source_labels: [__address__]
      target_label: __param_target
    - target_label: __address__
      replacement:  prometheus-blackbox-prometheus-blackbox-exporter:9115
    - source_labels: [__param_target]
      target_label: instance
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_service_name]
      target_label: kubernetes_service_name

- job_name: "blackbox-kubernetes-ingresses"
  metrics_path: /probe
  params:
    module: [http_2xx]
  kubernetes_sd_configs:
  - role: ingress
  relabel_configs:
  # Example relabel to probe only some ingresses that have "example.io/should_be_probed = true" annotation
  #  - source_labels: [__meta_kubernetes_ingress_annotation_example_io_should_be_probed]
  #    action: keep
  #    regex: true
    - source_labels:
        [
          __meta_kubernetes_ingress_scheme,
          __address__,
          __meta_kubernetes_ingress_path,
        ]
      regex: (.+);(.+);(.+)
      replacement: ${1}://${2}${3}
      target_label: __param_target
    - target_label: __address__
      replacement: prometheus-blackbox-prometheus-blackbox-exporter:9115
    - source_labels: [__param_target]
      target_label: instance
    - action: labelmap
      regex: __meta_kubernetes_ingress_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_ingress_name]
      target_label: ingress_name




- job_name: "blackbox-kubernetes-pods"
  metrics_path: /probe
  params:
    module: [http_2xx]
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  # Example relabel to scrape only pods that have
  # "example.io/should_be_scraped = true" annotation.
  #  - source_labels: [__meta_kubernetes_pod_annotation_example_io_should_be_scraped]
  #    action: keep
  #    regex: true
    - source_labels: [__address__]
      target_label: __param_target
    - target_label: __address__
      replacement:  prometheus-blackbox-prometheus-blackbox-exporter:9115
    - source_labels: [__param_target]
      replacement: ${1}/health
      target_label: instance
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      target_label: kubernetes_pod_name




# - job_name: "ingress-endpoint-status"
#   metrics_path: /probe
#   params:
#     module: [http_2xx]  # Look for a HTTP 200 response.
#   static_configs:
#     - targets:
#       - http://172.17.100.134/healthz
#       labels:
#         group: nginx-ingress
#   relabel_configs:
#     - source_labels: [__address__]
#       target_label: __param_target
#     - source_labels: [__param_target]
#       target_label: instance
#     - target_label: __address__
#       replacement: blackbox.monitoring:9115
# - job_name: "kubernetes-service-dns"
#   metrics_path: /probe
#   params:
#     module: [dns]
#   static_configs:
#   - targets:
#     - kube-dns.kube-system:53
#   relabel_configs:
#   - source_labels: [__address__]
#     target_label: __param_target
#   - source_labels: [__param_target]
#     target_label: instance
#   - target_label: __address__
#     replacement: blackbox.monitoring:9115